package daolivraria;


import java.awt.Image;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlo
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        busca_titulo_textfield = new javax.swing.JTextField();
        bt_buscar = new javax.swing.JButton();
        limpar_tabela = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id_livro_textfield = new javax.swing.JTextField();
        titulo_livro_textfield = new javax.swing.JTextField();
        editora_livro_textfield = new javax.swing.JTextField();
        autor_livro_textfield = new javax.swing.JTextField();
        ano_livro_textfield = new javax.swing.JTextField();
        id_genero_livro_textfield = new javax.swing.JTextField();
        preco_livro_textfield = new javax.swing.JTextField();
        reserva_livro_textfield = new javax.swing.JTextField();
        estoque_livro_textfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bt_pesquisar = new javax.swing.JButton();
        bt_apagar = new javax.swing.JButton();
        bt_atualizar = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        bt_limpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao_livro_textarea = new javax.swing.JTextArea();
        bt_primeiro = new javax.swing.JButton();
        bt_anterior = new javax.swing.JButton();
        bt_proximo = new javax.swing.JButton();
        bt_ultimo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_livros = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        tabela_busca_textfield = new javax.swing.JTextField();
        bt_buscartabela = new javax.swing.JButton();
        bt_limpartabela = new javax.swing.JButton();

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setText("Título:");

        busca_titulo_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busca_titulo_textfieldActionPerformed(evt);
            }
        });

        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        limpar_tabela.setText("Limpar");
        limpar_tabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_tabelaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LivrariaDAO / Carlo Nery de Lima Moro - 1548697");
        setResizable(false);

        jLabel1.setText("ID Livro:");

        jLabel2.setText("Título:");

        jLabel3.setText("Autor:");

        jLabel4.setText("Editora:");

        jLabel5.setText("Ano:");

        jLabel6.setText("ID Genero:");

        jLabel7.setText("Preço:");

        jLabel8.setText("Estoque:");

        jLabel9.setText("Reserva:");

        id_livro_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_livro_textfieldActionPerformed(evt);
            }
        });

        titulo_livro_textfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        editora_livro_textfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel10.setText("Descrição:");

        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        bt_apagar.setText("Apagar");
        bt_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_apagarActionPerformed(evt);
            }
        });

        bt_atualizar.setText("Atualizar");
        bt_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarActionPerformed(evt);
            }
        });

        bt_add.setText("Adicionar");
        bt_add.setToolTipText("");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        descricao_livro_textarea.setColumns(20);
        descricao_livro_textarea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        descricao_livro_textarea.setLineWrap(true);
        descricao_livro_textarea.setRows(5);
        descricao_livro_textarea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descricao_livro_textarea);

        bt_primeiro.setText("Primeiro");
        bt_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_primeiroActionPerformed(evt);
            }
        });

        bt_anterior.setText("Anterior");
        bt_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_anteriorActionPerformed(evt);
            }
        });

        bt_proximo.setText("Proximo");
        bt_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_proximoActionPerformed(evt);
            }
        });

        bt_ultimo.setText("Ultimo");
        bt_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ultimoActionPerformed(evt);
            }
        });

        tabela_livros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Livro_Id", "Título", "Autor", "Editora", "Ano", "Genero_Id", "Descrição", "Preço", "Estoque", "Reserva"
            }
        ));
        tabela_livros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabela_livros.setAutoscrolls(false);
        jScrollPane2.setViewportView(tabela_livros);

        jLabel12.setText("Título:");

        tabela_busca_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabela_busca_textfieldActionPerformed(evt);
            }
        });

        bt_buscartabela.setText("Buscar");
        bt_buscartabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscartabelaActionPerformed(evt);
            }
        });

        bt_limpartabela.setText("Limpar");
        bt_limpartabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpartabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bt_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(bt_anterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bt_apagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bt_proximo, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel2))
                                                .addGap(22, 22, 22))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(19, 19, 19)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(id_livro_textfield)
                                            .addComponent(autor_livro_textfield)
                                            .addComponent(titulo_livro_textfield)
                                            .addComponent(editora_livro_textfield)
                                            .addComponent(ano_livro_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(32, 32, 32)
                                        .addComponent(preco_livro_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bt_primeiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel10)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(bt_ultimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bt_limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(estoque_livro_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                        .addComponent(reserva_livro_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                        .addComponent(id_genero_livro_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1)))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bt_pesquisar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabela_busca_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_buscartabela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_limpartabela)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_livro_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisar))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo_livro_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editora_livro_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autor_livro_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ano_livro_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(preco_livro_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_add)
                            .addComponent(bt_atualizar)
                            .addComponent(bt_apagar)
                            .addComponent(bt_limpar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_primeiro)
                            .addComponent(bt_anterior)
                            .addComponent(bt_proximo)
                            .addComponent(bt_ultimo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(id_genero_livro_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reserva_livro_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estoque_livro_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_limpartabela)
                        .addComponent(jLabel12)
                        .addComponent(bt_buscartabela, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabela_busca_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_livro_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_livro_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_livro_textfieldActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        if (id_livro_textfield.getText().equals("") || (id_livro_textfield.getText() == null)) {
        }
        else {
            pesquisar();
        }
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void bt_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_apagarActionPerformed
        if (id_livro_textfield.getText().equals("") || (id_livro_textfield.getText() == null)) {
        }
        else {
            apagar();
        }
    }//GEN-LAST:event_bt_apagarActionPerformed

    private void bt_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarActionPerformed
        if (id_livro_textfield.getText().equals("") || (id_livro_textfield.getText() == null)) {
        }
        else {
            botao_atualizar();
        }
    }//GEN-LAST:event_bt_atualizarActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        if (id_livro_textfield.getText().equals("") || (id_livro_textfield.getText() == null)) {
        }
        else {
            add();
        }
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed
        limpa();
    }//GEN-LAST:event_bt_limparActionPerformed

    private void busca_titulo_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busca_titulo_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busca_titulo_textfieldActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed

    }//GEN-LAST:event_bt_buscarActionPerformed

    private void limpar_tabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_tabelaActionPerformed
        DefaultTableModel model = (DefaultTableModel) GUI.tabela_livros.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_limpar_tabelaActionPerformed

    private void tabela_busca_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabela_busca_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabela_busca_textfieldActionPerformed

    private void bt_buscartabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscartabelaActionPerformed
        if (!(tabela_busca_textfield.getText() == null) && !(tabela_busca_textfield.getText().equals(""))) {
            LivroDAO livrodao = new LivroDAO();
            LivroTO livro = new LivroTO();
            ArrayList<LivroTO> lista = new ArrayList<LivroTO>();
            lista = livrodao.buscatitulo(tabela_busca_textfield.getText());
            setatabela(lista);
        }
    }//GEN-LAST:event_bt_buscartabelaActionPerformed

    private void bt_limpartabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpartabelaActionPerformed
        DefaultTableModel model = (DefaultTableModel) GUI.tabela_livros.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_bt_limpartabelaActionPerformed

    private void bt_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ultimoActionPerformed
        LivroDAO livrodao = new LivroDAO();
        LivroTO livro = new LivroTO();
        livro = livrodao.last();
        setainformacoes(livro);
    }//GEN-LAST:event_bt_ultimoActionPerformed

    private void bt_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_proximoActionPerformed
        LivroDAO livrodao = new LivroDAO();
        LivroTO livro = new LivroTO();
        
        if (id_livro_textfield.getText().equals("")) {
            livro = livrodao.last();
            setainformacoes(livro);
        }
        else {
            livro = livrodao.next(Integer.parseInt(id_livro_textfield.getText()));
            setainformacoes(livro);
        }    
    }//GEN-LAST:event_bt_proximoActionPerformed

    private void bt_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_anteriorActionPerformed
        LivroDAO livrodao = new LivroDAO();
        LivroTO livro = new LivroTO();
        
        if (id_livro_textfield.getText().equals("")) {
            livro = livrodao.first();
            setainformacoes(livro);
        }
        else {
            livro = livrodao.previous(Integer.parseInt(id_livro_textfield.getText()));
            setainformacoes(livro);
        } 
    }//GEN-LAST:event_bt_anteriorActionPerformed

    private void bt_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_primeiroActionPerformed
        LivroDAO livrodao = new LivroDAO();
        LivroTO livro = new LivroTO();
        livro = livrodao.first();
        setainformacoes(livro);
    }//GEN-LAST:event_bt_primeiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
        public void setainformacoes(LivroTO livro) {
            try {
                ano_livro_textfield.setText(Integer.toString(livro.getAno()));
                autor_livro_textfield.setText(livro.getAutor());
                editora_livro_textfield.setText(livro.getEditora());
                estoque_livro_textfield.setText(Integer.toString(livro.getEstoque()));
                id_genero_livro_textfield.setText(Integer.toString(livro.getGenero_id()));
                preco_livro_textfield.setText(Double.toString(livro.getPreco()));
                reserva_livro_textfield.setText(Integer.toString(livro.getReserva()));
                titulo_livro_textfield.setText(livro.getTitulo());
                descricao_livro_textarea.setText(livro.getDescricao());
                id_livro_textfield.setText(Integer.toString(livro.getLivro_id()));
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(rootPane, "Primeiro/Ultimo livro já atingido!");
            }
        }
        
        public void setatabela(ArrayList<LivroTO> lista) {
            DefaultTableModel model = (DefaultTableModel) tabela_livros.getModel();
            for(int i=0;i<lista.size();i++){
            model.addRow(new Object[]{lista.get(i).getLivro_id(), lista.get(i).getTitulo(), lista.get(i).getAutor(),
                                          lista.get(i).getEditora(), lista.get(i).getAno(), lista.get(i).getGenero_id(),
                                          lista.get(i).getDescricao(), lista.get(i).getPreco(), lista.get(i).getEstoque(),
                                          lista.get(i).getReserva()});
            }
        }
        
        public void pesquisar() {        
        try {
            LivroTO livro = new LivroTO();
            LivroDAO livrodao = new LivroDAO();
            livro = livrodao.find(Integer.parseInt(id_livro_textfield.getText()));
            if(livro != null){
                limpa();
                ano_livro_textfield.setText(Integer.toString(livro.getAno()));
                autor_livro_textfield.setText(livro.getAutor());
                editora_livro_textfield.setText(livro.getEditora());
                estoque_livro_textfield.setText(Integer.toString(livro.getEstoque()));
                id_genero_livro_textfield.setText(Integer.toString(livro.getGenero_id()));
                preco_livro_textfield.setText(Double.toString(livro.getPreco()));
                reserva_livro_textfield.setText(Integer.toString(livro.getReserva()));
                titulo_livro_textfield.setText(livro.getTitulo());
                descricao_livro_textarea.setText(livro.getDescricao());
                id_livro_textfield.setText(Integer.toString(livro.getLivro_id()));
                //capa_livro.setIcon(livro.getCapa());
            } else
                JOptionPane.showMessageDialog(rootPane, "Livro ID não cadastrado!");
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, e, "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void botao_atualizar(){
        try {
            LivroTO livro = new LivroTO();
            LivroDAO livrodao = new LivroDAO();
            livro = livrodao.find(Integer.parseInt(id_livro_textfield.getText()));
            
            if(livro == null){
                add();
            }else{
                atualizar_acao();
            }
            limpa();
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, e, "Erro", JOptionPane.INFORMATION_MESSAGE);
        }        
    }
    
    public void add(){
        LivroTO livro = new LivroTO();
        LivroDAO livrodao = new LivroDAO();
        livro = livrodao.find(Integer.parseInt(id_livro_textfield.getText()));
        
        if (livro == null) {
            livro.setAno(Integer.parseInt(ano_livro_textfield.getText()));
            livro.setAutor(autor_livro_textfield.getText());
            livro.setDescricao(descricao_livro_textarea.getText());
            livro.setEditora(editora_livro_textfield.getText());
            livro.setEstoque(Integer.parseInt(estoque_livro_textfield.getText()));
            livro.setGenero_id(Integer.parseInt(id_genero_livro_textfield.getText()));  
            livro.setLivro_id(Integer.parseInt(id_livro_textfield.getText())); 
            livro.setPreco(Double.parseDouble(preco_livro_textfield.getText()));        
            livro.setReserva(Integer.parseInt(reserva_livro_textfield.getText()));         
            livro.setTitulo(titulo_livro_textfield.getText());        

            try {
                livrodao.insert(livro);
                JOptionPane.showMessageDialog(rootPane, "Livro cadastrado!");
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(null, e, "Erro", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Livro já cadastrado!");
        }
    }
    
    public void atualizar_acao(){
        LivroTO livro = new LivroTO();
        
        livro.setAno(Integer.parseInt(ano_livro_textfield.getText()));
        livro.setAutor(autor_livro_textfield.getText());
        livro.setDescricao(descricao_livro_textarea.getText());
        livro.setEditora(editora_livro_textfield.getText());
        livro.setEstoque(Integer.parseInt(estoque_livro_textfield.getText()));
        livro.setGenero_id(Integer.parseInt(id_genero_livro_textfield.getText()));  
        livro.setLivro_id(Integer.parseInt(id_livro_textfield.getText())); 
        livro.setPreco(Double.parseDouble(preco_livro_textfield.getText()));        
        livro.setReserva(Integer.parseInt(reserva_livro_textfield.getText()));         
        livro.setTitulo(titulo_livro_textfield.getText());  
        
        try {
            LivroDAO livrodao = new LivroDAO();
            livrodao.update(livro);
            JOptionPane.showMessageDialog(rootPane, "Livro atualizado!");
            limpa();
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, e, "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void apagar(){
        try {
            LivroTO livro = new LivroTO();
            LivroDAO livrodao = new LivroDAO();
            livro = livrodao.find(Integer.parseInt(id_livro_textfield.getText()));
            
            if(livro != null){
                livro.setLivro_id(Integer.parseInt(id_livro_textfield.getText())); 

                livrodao.delete(livro);
                JOptionPane.showMessageDialog(rootPane, "Livro deletado!");
                limpa();
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Livro não está cadastrado!");
            }
       } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, e, "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void limpa() {
        id_livro_textfield.setText(null);
        titulo_livro_textfield.setText(null);
        editora_livro_textfield.setText(null);
        autor_livro_textfield.setText(null);
        ano_livro_textfield.setText(null);
        preco_livro_textfield.setText(null);
        id_genero_livro_textfield.setText(null);
        reserva_livro_textfield.setText(null);
        estoque_livro_textfield.setText(null);
        descricao_livro_textarea.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField ano_livro_textfield;
    public static javax.swing.JTextField autor_livro_textfield;
    public static javax.swing.JButton bt_add;
    public static javax.swing.JButton bt_anterior;
    public static javax.swing.JButton bt_apagar;
    public static javax.swing.JButton bt_atualizar;
    private javax.swing.JButton bt_buscar;
    public static javax.swing.JButton bt_buscartabela;
    public static javax.swing.JButton bt_limpar;
    public static javax.swing.JButton bt_limpartabela;
    public static javax.swing.JButton bt_pesquisar;
    public static javax.swing.JButton bt_primeiro;
    public static javax.swing.JButton bt_proximo;
    public static javax.swing.JButton bt_ultimo;
    private javax.swing.JTextField busca_titulo_textfield;
    public static javax.swing.JTextArea descricao_livro_textarea;
    public static javax.swing.JTextField editora_livro_textfield;
    public static javax.swing.JTextField estoque_livro_textfield;
    public static javax.swing.JTextField id_genero_livro_textfield;
    public static javax.swing.JTextField id_livro_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator4;
    public static javax.swing.JButton limpar_tabela;
    public static javax.swing.JTextField preco_livro_textfield;
    public static javax.swing.JTextField reserva_livro_textfield;
    public static javax.swing.JTextField tabela_busca_textfield;
    public static javax.swing.JTable tabela_livros;
    public static javax.swing.JTextField titulo_livro_textfield;
    // End of variables declaration//GEN-END:variables
}
